import fs from "node:fs";
import { splitLearnerBody } from "./claims.js";
import { inventoryById, anchorForKp } from "./inventory.js";
import { normalizeWhitespace } from "./anchors.js";

const MMHG_RE = />\s*(\d+(?:[.,]\d+)?)\s*mmHg/gi;

/**
 * ground(claims, inventory, evidence) -> groundingResult
 *
 * Deterministic mode: threshold numeric match for sourced high-specificity claims.
 * Semantic mode (bootstrap): reads optional fixture verdicts for bridging claims.
 */
export function groundDeterministic({ filePaths, inventory, sourceMeta }) {
  const errors = [];
  const verdicts = {};
  const kpMap = inventoryById(inventory);
  const kp041 = kpMap.get("KP-041");
  const anchor = anchorForKp(kp041, sourceMeta.edition);
  const expectedThreshold = extractThresholdFromQuote(anchor?.quote);

  if (expectedThreshold == null) {
    errors.push("grounding: cannot extract threshold from KP-041 anchor");
  }

  const mechRaw = fs.readFileSync(filePaths.mechanisms, "utf8");
  const { body } = splitLearnerBody(mechRaw);

  const thresholdClaim = extractThresholdFromText(body, "cb-oap-threshold");
  if (thresholdClaim == null) {
    errors.push("grounding: cb-oap-threshold claim text missing threshold");
  } else if (expectedThreshold != null && thresholdClaim !== expectedThreshold) {
    verdicts["cb-oap-threshold"] = {
      mode: "deterministic",
      status: "fail",
      expected_mmHg: expectedThreshold,
      found_mmHg: thresholdClaim,
    };
    errors.push(
      `grounding: threshold mismatch (expected >${expectedThreshold}, found >${thresholdClaim})`
    );
  } else {
    verdicts["cb-oap-threshold"] = {
      mode: "deterministic",
      status: "pass",
      expected_mmHg: expectedThreshold,
      found_mmHg: thresholdClaim,
    };
  }

  return {
    ok: errors.length === 0,
    errors,
    verdicts,
    status: errors.length === 0 ? "pass" : "fail",
  };
}

export function extractThresholdFromQuote(quote) {
  if (!quote) return null;
  const m = quote.match(/>\s*(\d+(?:[.,]\d+)?)\s*mmHg/i);
  return m ? Number(m[1].replace(",", ".")) : null;
}

function extractThresholdFromText(body, locatorId) {
  const idx = body.indexOf(`{#${locatorId}}`);
  const slice = idx === -1 ? body : body.slice(0, idx + 20);
  const search = idx === -1 ? body : body.slice(Math.max(0, idx - 200), idx + 5);
  const m = search.match(/>\s*(\d+(?:[.,]\d+)?)\s*mmHg/i);
  return m ? Number(m[1].replace(",", ".")) : null;
}

export function mergeSemanticGrounding(deterministicResult, semanticFixture) {
  const verdicts = { ...deterministicResult.verdicts };
  const errors = [...deterministicResult.errors];

  for (const [id, v] of Object.entries(semanticFixture?.bridging || {})) {
    verdicts[id] = { mode: "semantic-bootstrap", ...v };
    if (v.status === "fail") {
      errors.push(`grounding semantic: ${id} failed`);
    }
  }

  return {
    ok: errors.length === 0,
    errors,
    verdicts,
    status: errors.length === 0 ? "pass" : "fail",
    note:
      "Semantic bridging checks use bootstrap fixtures until LLM runtime is wired.",
  };
}

export function writeGroundingYaml(path, result) {
  const lines = [
    "# Generated by lou-build ground() — do not hand-edit",
    `status: ${result.status}`,
    "verdicts:",
  ];
  for (const [id, v] of Object.entries(result.verdicts)) {
    lines.push(`  ${id}:`);
    for (const [k, val] of Object.entries(v)) {
      lines.push(`    ${k}: ${JSON.stringify(val)}`);
    }
  }
  if (result.note) lines.push(`note: ${JSON.stringify(result.note)}`);
  fs.writeFileSync(path, lines.join("\n") + "\n");
}
