import fs from "node:fs";
import { splitLearnerBody, indexProjectionBodies } from "./claims.js";
import { inventoryById, anchorForKp } from "./inventory.js";
import {
  bootstrapSemanticAllowlist,
  bootstrapSemanticVerdicts,
} from "./chapter-config.js";

const THRESHOLD_MMHG_RE = />\s*(\d+(?:[.,]\d+)?)\s*mmHg/gi;

/**
 * Deterministic grounding over sourced high-specificity claims.
 * Currently implements threshold-mmHg consistency checks derived from KP anchors.
 */
export function groundDeterministic({
  projectionResults,
  inventory,
  sourceMeta,
}) {
  const errors = [];
  const verdicts = {};
  const kpMap = inventoryById(inventory);
  const bodiesByClaim = indexProjectionBodies(projectionResults || []);

  for (const [claimId, ctx] of bodiesByClaim) {
    const claim = ctx.claim;
    if (claim.class !== "sourced") continue;

    for (const kpId of claim.kp || []) {
      const kp = kpMap.get(kpId);
      const anchor = anchorForKp(kp, sourceMeta.edition);
      const expectedThreshold = extractThresholdFromQuote(anchor?.quote);
      if (expectedThreshold == null) continue;

      const foundThreshold = extractThresholdNearLocator(ctx.body, claimId);
      if (foundThreshold == null) continue;

      if (foundThreshold !== expectedThreshold) {
        verdicts[claimId] = {
          mode: "deterministic",
          rule: "threshold-mmHg",
          status: "fail",
          kp: kpId,
          expected_mmHg: expectedThreshold,
          found_mmHg: foundThreshold,
        };
        errors.push(
          `grounding: ${claimId} threshold mismatch (expected >${expectedThreshold}, found >${foundThreshold})`
        );
      } else {
        verdicts[claimId] = {
          mode: "deterministic",
          rule: "threshold-mmHg",
          status: "pass",
          kp: kpId,
          expected_mmHg: expectedThreshold,
          found_mmHg: foundThreshold,
        };
      }
    }
  }

  return {
    ok: errors.length === 0,
    errors,
    verdicts,
    status: errors.length === 0 ? "pass" : "fail",
  };
}

export function extractThresholdFromQuote(quote) {
  if (!quote) return null;
  const m = quote.match(/>\s*(\d+(?:[.,]\d+)?)\s*mmHg/i);
  return m ? Number(m[1].replace(",", ".")) : null;
}

function extractThresholdNearLocator(body, locatorId) {
  const idx = body.indexOf(`{#${locatorId}}`);
  const search =
    idx === -1 ? body : body.slice(Math.max(0, idx - 200), idx + 5);
  const m = search.match(/>\s*(\d+(?:[.,]\d+)?)\s*mmHg/i);
  return m ? Number(m[1].replace(",", ".")) : null;
}

/**
 * Semantic grounding merge.
 * Bootstrap verdicts apply ONLY to explicitly allowlisted claim IDs.
 * All other bridging/sourced claims without independent verdicts block publication.
 */
export function mergeSemanticGrounding(
  deterministicResult,
  { projectionResults, packageConfig }
) {
  const verdicts = { ...deterministicResult.verdicts };
  const errors = [...deterministicResult.errors];
  const allowlist = bootstrapSemanticAllowlist(packageConfig);
  const bootstrapVerdicts = bootstrapSemanticVerdicts(packageConfig);

  const bridgingClaims = [];
  for (const pr of projectionResults || []) {
    for (const claim of pr.claims || []) {
      if (claim.class === "bridging" || claim.class === "scaffolding") {
        bridgingClaims.push(claim);
      }
    }
  }

  for (const claim of bridgingClaims) {
    if (allowlist.has(claim.id) && bootstrapVerdicts[claim.id]) {
      verdicts[claim.id] = {
        mode: "semantic-bootstrap",
        ...bootstrapVerdicts[claim.id],
      };
      if (bootstrapVerdicts[claim.id].status === "fail") {
        errors.push(`grounding semantic: ${claim.id} failed`);
      }
      continue;
    }

    verdicts[claim.id] = {
      mode: "semantic",
      status: "pending",
      note: "Awaiting independent semantic grounding pass",
    };
    errors.push(
      `grounding semantic: ${claim.id} lacks independent verdict (not bootstrap-allowlisted)`
    );
  }

  const hasBootstrap = allowlist.size > 0;
  const note = hasBootstrap
    ? "Bootstrap semantic verdicts apply only to explicitly allowlisted claim IDs until LLM runtime is wired."
    : "Semantic grounding requires independent verdicts for all non-deterministic claims.";

  return {
    ok: errors.length === 0,
    errors,
    verdicts,
    status: errors.length === 0 ? "pass" : "fail",
    note,
  };
}

export function writeGroundingYaml(path, result) {
  const lines = [
    "# Generated by lou-build ground() — do not hand-edit",
    `status: ${result.status}`,
    "verdicts:",
  ];
  for (const [id, v] of Object.entries(result.verdicts)) {
    lines.push(`  ${id}:`);
    for (const [k, val] of Object.entries(v)) {
      lines.push(`    ${k}: ${JSON.stringify(val)}`);
    }
  }
  if (result.note) lines.push(`note: ${JSON.stringify(result.note)}`);
  fs.writeFileSync(path, lines.join("\n") + "\n");
}
